### ISSUE TITLE
Reforking turtle

### ISSUE THREAD

**Issue by LeoCornelius** [kegcoin-project/kegcoin-gold-old#14]
Today i will  be reforking turtlecoin to get rid of our stupid little bugs.
i will then:
* Add Kify v1 + v2
* Add Keghash (maybe)
* Add our custom block reward algo 
* Add any snippets of code from the old repo

**Comment by LeoCornelius** [comment]
I will rename this to kegcoin-gold-old for reference

**Comment by LacroyPlays** [comment]
ah yeah man, i made a commit to the website btw might wanna update ;D

**Comment by TheDevMinerTV** [comment]
yeet

**Comment by LeoCornelius** [comment]
@LacroyPlays will do thanks

**Comment by LeoCornelius** [comment]
done! Repo moved to https://github.com/kegcoin-project/kegcoin-gold (this is now called https://github.com/kegcoin-project/kegcoin-gold-old)
